### ISSUE TITLE
Author permission and licenses

### ISSUE THREAD

**Issue by brson** [brson/rust-anthology#5]
Once a chapter has been [preliminarily added to the book](https://github.com/brson/rust-anthology/issues/3) (or even better - before), we need to make sure they are cool with being included, and find out the license they release their work under.

Information they should understand:
- At this stage, we are not promising to publish their piece - it is still early in the process, and it may be later removed for editorial reasons.
- For simplicity, unless they state otherwise, this permission covers _all_ their written work related to Rust, unless that work has been published in some commercial context.
- They retain all rights to their work, as well as any edits made by others.
- They will have another opportunity before final publication to approve their chapters.
- If they have no license preference we recommend [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/).

To get permission, contact them privately and ask the to post their consent to this thread, like "I consent to have my Rust writing published in Rust Anthology under the terms of the $LICENSE license".
## Authors and licenses
- [ ] Aaron Turon
- [ ] Andre Bogus
- [ ] Andrew Hobden
- [ ] Huon Wilson
- [x] Manish Goregaokar

**Comment by carols10cents** [comment]
The README seems to imply that consent will be opt-out, but this issue suggests opt-in... I would like to strongly recommend using opt-in for this project.

**Comment by Manishearth** [comment]
I consent to have my Rust writing published in Rust Anthology under the terms of the MIT, Apache v2.0, MPL, or CC-BY-4.0 (or CC-BY-SA-4.0) licenses.

**Comment by brson** [comment]
> The README seems to imply that consent will be opt-out, but this issue suggests opt-in... I would like to strongly recommend using opt-in for this project.

@carols10cents That's not the intent. Rather, that I don't intend to get authors permission before starting to integrate their work (mostly because I don't want to be in a situation where I ask for permission often then not use their work - seems disappointing). The way I've [structured](https://github.com/brson/rust-anthology/issues/2) the process currently is to do a round of cursory review, merge the initial, unedited text for stuff that looks good, then circle back and ask for permission.

I do recognize that that leaves a window where I am publishing people's work to the web without their permission (which in situations where authors haven't already declared a license is not actually legal). It wouldn't be too hard to structure the process so that on the initial merge PR the author gets pinged for permission. I'll pursue that.
